### PR TITLE
Enable CD

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by timja** [comment]
Err:

```
2022-11-05T19:57:30.112Z] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (display-info) @ cloud-stats ---

[2022-11-05T19:57:30.923Z] [INFO] Adding ignore: module-info

[2022-11-05T19:57:30.923Z] [INFO] Restricted to JDK 8 yet org.jenkins-ci.main:websocket-spi:jar:2.361.3:provided contains jenkins/websocket/Provider$Handler.class targeted to JDK 11

[2022-11-05T19:57:30.923Z] [INFO] Restricted to JDK 8 yet org.jenkins-ci:commons-jelly:jar:1.1-jenkins-20220630:provided contains org/apache/commons/jelly/util/TagUtils.class targeted to JDK 11
```

**Comment by timja** [comment]
Master is failing for the same issue

**Comment by MarkEWaite** [comment]
> Master is failing for the same issue

Yes, sorry about that.  I was too aggressive in merging the CI checks of Java 8, Java 11, and Java 17.  Those checks need #31.  It has been merged now.

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by MarkEWaite** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/2935 has been submitted to enable continuous delivery.

**Comment by MarkEWaite** [comment]
> [jenkins-infra/repository-permissions-updater#2935](https://github.com/jenkins-infra/repository-permissions-updater/pull/2935) has been submitted to enable continuous delivery.

Merged and I've confirmed that the necessary items are visible in the settings of this repository.  I'd like to merge #35 before this is merged

**Comment by timja** [comment]
Ready to ship?

**Pull request merged**
